version: '3.8'

services:

  frontend:
    container_name: docker_chatbot_frontend
    build:
      context: frontend    
      target: development
    working_dir: /code/frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/code
      - /code/node_modules
    networks:
      frontend:
        ipv4_address: 192.30.0.7
    environment:
       - CHOKIDAR_USEPOLLING=true
    # env_file:
    #    - ./frontend/.env

networks:
  frontend:
    driver: bridge
    ipam:
      config:
        - subnet: 192.30.0.0/24